using Pkg
Pkg.add("Glob")
Pkg.add("NCDatasets")
Pkg.add("Plots")
Pkg.add("Statistics")
Pkg.add("BenchmarkTools")
Pkg.add("Dates")
Pkg.add("DataStructures")
Pkg.add("DelimitedFiles")
Pkg.add("NaNMath")
Pkg.add("StatsBase")
Pkg.add("ColorSchemeTools")
Pkg.add("LaTeXStrings")
Pkg.add("LsqFit")
Pkg.add("Base")
Pkg.add("Interpolations")
Pkg.add("Geodesy")
Pkg.add("Revise")
Pkg.add("OhMyREPL")
Pkg.add("JuMP")
Pkg.add("PyPlot")
Pkg.add("PyCall")
Pkg.add("Images")
Pkg.add("Images")
Pkg.add("ImageView")

